env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
- dir: pkg
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
  goarch:
    - amd64
    - arm64
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
    - go mod tidy
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
    - goos: windows
      format: zip
    files:
      - README.md
      - LICENSE
release:
  github:
    owner: tedsmitt
    name: ecsgo
brews:
  - name: ecsgo
    tap:
      owner: tedsmitt
      name: homebrew-ecsgo
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: tedsmitt
      email: edwardsmith92@outlook.com
    description: "Interactive CLI tool which acts as a wrapper around the ECS ExecuteCommand API."
    license: Apache2
    test: |
      system "#{bin}/goreleaser -v"
    dependencies:
    - name: go