name: Run Tests

on:
  push:
    branches:
      - "**"
    paths:
      - "**.go"
  pull_request:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Install dependencies
        run: |
          go mod tidy
          # reset go.sum and go.mod so goreleaser won't complain about dirty git state
          git checkout HEAD -- go.sum go.mod

      - name: Run tests
        run: go test -v ./internal

      - name: Build
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: --snapshot --skip-publish --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
